# -*- coding: utf-8 -*-
"""
/***************************************************************************
 FlowMapper
                                 A QGIS plugin
 Flow map creating via spiral trees
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2022-03-08
        copyright            : (C) 2022 by Gleb Pinigin
        email                : pinigin1514@live.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load FlowMapper class from file FlowMapper.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .flow_mapper import FlowMapper
    return FlowMapper(iface)
