# -*- coding: utf-8 -*-
"""
/***************************************************************************
 FlowMapperDockWidget
                                 A QGIS plugin
 Flow map creating via spiral trees
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2022-03-08
        git sha              : $Format:%H$
        copyright            : (C) 2022 by Gleb Pinigin
        email                : pinigin1514@live.com
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

import os

from qgis.PyQt import QtGui, QtWidgets, uic
from qgis.PyQt.QtCore import pyqtSignal

from .ioqgis.do_with_qgis import do

FORM_CLASS, _ = uic.loadUiType(os.path.join(
    os.path.dirname(__file__), 'flow_mapper_dockwidget_base.ui'))


class FlowMapperDockWidget(QtWidgets.QDockWidget, FORM_CLASS):

    closingPlugin = pyqtSignal()

    def __init__(self, parent=None):
        """Constructor."""
        super(FlowMapperDockWidget, self).__init__(parent)
        # Set up the user interface from Designer.
        # After setupUI you can access any designer object by doing
        # self.<objectname>, and you can use autoconnect slots - see
        # http://doc.qt.io/qt-5/designer-using-a-ui-file.html
        # #widgets-and-dialogs-with-auto-connect
        self.setupUi(self)
        self.out_path.textChanged[str].connect(self.editingFinished)
        self.do_main.clicked.connect(self.run)

    def set_iface(self, iface):
        self.iface = iface
        return

    def editingFinished(self, text):
        self.path = text

    def run(self):
        do(self.iface, self.path)

    def closeEvent(self, event):
        self.closingPlugin.emit()
        event.accept()
